services:
  # PHP-FPM сервис
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bastion-cms-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bastion-cms
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bastion-cms
    depends_on:
      - mysql

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: bastion-cms-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - bastion-cms
    depends_on:
      - app

  # MySQL база данных
  mysql:
    image: mysql:8.2
    container_name: bastion-cms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bastion-cms
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bastion-cms

  # phpMyAdmin для управления БД
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bastion-cms-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - bastion-cms
    depends_on:
      - mysql

  # Node.js для frontend разработки
  node:
    image: node:23-alpine
    container_name: bastion-cms-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - bastion-cms
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # Redis для кеширования и очередей
  redis:
    image: redis:7-alpine
    container_name: bastion-cms-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bastion-cms

networks:
  bastion-cms:
    driver: bridge

volumes:
  mysql_data:
    driver: local 