services:
  app:
    user: "1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bastion_app
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=bastion
      - DB_USERNAME=bastion
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - bastion_net

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: bastion_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - bastion_net

  mysql:
    image: mysql:8.2.0
    container_name: bastion_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bastion
      MYSQL_USER: bastion
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bastion_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bastion_phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
      POST_MAX_SIZE: 500M
      UPLOAD_MAX_FILESIZE: 500M
    volumes:
      - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    depends_on:
      - mysql
    networks:
      - bastion_net

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  bastion_net:
    driver: bridge
