services:
  app:
    user: "1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - laravel_net

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx
    ports:
      - "8443:443"   # HTTPS
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_net

  mysql:
    image: mysql:8.2.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - laravel_net

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  laravel_net:
    driver: bridge
