version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html:delegated
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - laravel_net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx
    ports:
      - "8000:80"    # HTTP
      - "8443:443"   # HTTPS
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_net

  mysql:
    image: mysql:8.2.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - laravel_net

volumes:
  mysql_data:

networks:
  laravel_net:
    driver: bridge
